#!/usr/bin/env python3
import argparse
import sys
from pathlib import Path

from validate_routes import load_and_validate

ACME_ROOT = "/usr/share/nginx/html"
CERT_ROOT = "/etc/letsencrypt/live"


def server_names(route):
    return " ".join([route["hostname"], *route.get("legacy_aliases", [])])


def http_config(route):
    names = server_names(route)
    return f'''# Generated by Vitrine IA Pro Routing Registry. Do not edit by hand.\n# route_id: {route["id"]}\nserver {{\n    listen 80;\n    listen [::]:80;\n    server_name {names};\n\n    location ^~ /.well-known/acme-challenge/ {{\n        root {ACME_ROOT};\n        default_type text/plain;\n        try_files $uri =404;\n    }}\n\n    location / {{\n        return 301 https://$host$request_uri;\n    }}\n}}\n'''


def https_config(route):
    names = server_names(route)
    host = route["hostname"]
    upstream = route["upstream"]
    return f'''# Generated by Vitrine IA Pro Routing Registry. Do not edit by hand.\n# route_id: {route["id"]}\nserver {{\n    listen 443 ssl;\n    listen [::]:443 ssl;\n    http2 on;\n    server_name {names};\n\n    ssl_certificate {CERT_ROOT}/{host}/fullchain.pem;\n    ssl_certificate_key {CERT_ROOT}/{host}/privkey.pem;\n\n    location / {{\n        proxy_pass http://{upstream};\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_set_header X-Forwarded-Host $host;\n        proxy_set_header X-Forwarded-Port $server_port;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection "upgrade";\n        proxy_read_timeout 120s;\n        proxy_send_timeout 120s;\n    }}\n}}\n'''


def render(route, phase):
    if phase == "http":
        return http_config(route)
    if phase == "https":
        return https_config(route)
    return http_config(route) + "\n" + https_config(route)


def main():
    parser = argparse.ArgumentParser(description="Gera vhosts Nginx a partir do Routing Registry")
    parser.add_argument("registry", nargs="?", default="routes.json")
    parser.add_argument("--output", default="generated")
    parser.add_argument("--phase", choices=("http", "https", "full"), default="full")
    parser.add_argument("--route-id")
    args = parser.parse_args()

    try:
        data, errors, warnings = load_and_validate(args.registry)
    except Exception as exc:
        print(f"ERRO: {exc}", file=sys.stderr)
        return 2
    for warning in warnings:
        print(f"AVISO: {warning}")
    if errors:
        for error in errors:
            print(f"ERRO: {error}", file=sys.stderr)
        return 1

    routes = [r for r in data["routes"] if r.get("status") != "disabled"]
    if args.route_id:
        routes = [r for r in routes if r["id"] == args.route_id]
        if not routes:
            print(f"ERRO: route-id nao encontrado: {args.route_id}", file=sys.stderr)
            return 1

    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    for route in routes:
        path = out / f'{route["id"]}.conf'
        path.write_text(render(route, args.phase), encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
