FROM python:3.12-alpine

RUN addgroup -S -g 8871 breakglass && adduser -S -D -H -u 8871 -G breakglass breakglass
WORKDIR /app
COPY break-glass/homologation.py /app/homologation.py
USER breakglass
CMD ["python", "/app/homologation.py"]
