from __future__ import annotations

import json
import subprocess
import sys

TARGET_CONTAINER = "cursos_ia_mvp_hml"

PHP = r'''require_once '/var/www/html/core_model.php'; require_once '/var/www/html/ai_generator.php'; require_once '/var/www/html/course_engine.php'; require_once '/var/www/html/academic_model.php'; require_once '/var/www/html/academic_eligibility.php'; require_once '/var/www/html/finance_model.php'; require_once '/var/www/html/video_model.php';
$checks=[];$courseId=0;$studentId=0;$failed=false;
function ck(&$c,$n,$ok,$d=''){ $c[]=['gate'=>$n,'status'=>$ok?'PASS':'FAIL','detail'=>$d]; if(!$ok) throw new RuntimeException($n.':'.$d); }
try{$pdo=new PDO('mysql:host='.(getenv('DB_HOST')?:'db').';dbname='.(getenv('DB_DATABASE')?:'cursos_ia_mvp').';charset=utf8mb4',getenv('DB_USERNAME')?:'cursos_ia',getenv('DB_PASSWORD')?:'',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);ensureCoreCourseModel($pdo);ensureAcademicModel($pdo);ensureFinanceModel($pdo);ensureVideoModel($pdo);ck($checks,'db',(bool)$pdo->query('SELECT 1')->fetchColumn());ck($checks,'broker_ready',aiIsReady()&&aiConfig()['mode']==='broker',aiProviderLabel());
$s=$pdo->prepare('INSERT INTO courses(title,audience,objective,course_level,desired_hours,modality,language_style,expected_outcome) VALUES(?,?,?,?,?,?,?,?)');$s->execute(['[E2E HML] '.gmdate('Ymd-His'),'Homologação','Validar fluxo integral.','iniciante',2,'online','didatica','Validar gates sem envio real.']);$courseId=(int)$pdo->lastInsertId();$course=$pdo->query('SELECT * FROM courses WHERE id='.$courseId)->fetch();ck($checks,'course_created',$courseId>0);
$src='Fonte controlada de homologação. O processo possui compreensão do objetivo, aplicação segura, revisão humana, avaliação final e preparação de vídeo sem envio real. Todo conteúdo deve permanecer limitado a estas informações.';$s=$pdo->prepare("INSERT INTO sources(course_id,source_type,name,content,processing_status,quality_status,quality_note,active_for_generation,content_hash) VALUES(?,?,?,?,'processado','boa','E2E',1,?)");$s->execute([$courseId,'texto','Fonte E2E',$src,hash('sha256',$src)]);$sources=$pdo->query('SELECT * FROM sources WHERE course_id='.$courseId)->fetchAll();ck($checks,'source_active',count($sources)===1);
$st=generateCourseWithAI($course,$sources);ck($checks,'broker_course_generation',count($st['modules']??[])>=2,'modules='.count($st['modules']??[]));foreach($st['modules'] as $mi=>$m){$s=$pdo->prepare('INSERT INTO modules(course_id,position,title,objective) VALUES(?,?,?,?)');$s->execute([$courseId,$mi+1,$m['title'],$m['objective']]);$mid=(int)$pdo->lastInsertId();foreach($m['lessons'] as $li=>$l){$s=$pdo->prepare("INSERT INTO lessons(module_id,position,title,objective,script,review_status) VALUES(?,?,?,?,?,'pendente')");$s->execute([$mid,$li+1,$l['title'],$l['objective'],$l['script']]);}}$lessons=(int)$pdo->query('SELECT COUNT(*) FROM lessons l JOIN modules m ON m.id=l.module_id WHERE m.course_id='.$courseId)->fetchColumn();ck($checks,'lessons_created',$lessons>0,'lessons='.$lessons);
$pdo->exec("CREATE TABLE IF NOT EXISTS course_assets (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,course_id INT UNSIGNED NOT NULL,asset_type VARCHAR(40) NOT NULL,title VARCHAR(180) NOT NULL,content LONGTEXT NOT NULL,status VARCHAR(40) NOT NULL DEFAULT 'rascunho',engine_mode VARCHAR(60) NOT NULL DEFAULT 'grounded_editorial_v0.4',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_course_asset(course_id,asset_type),CONSTRAINT fk_assets_course FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$vs=videoCourseState($pdo,$courseId);ck($checks,'blocked_before_pedagogy',!$vs['pedagogical_ok']&&!$vs['package_ok']);$pdo->prepare("UPDATE lessons l JOIN modules m ON m.id=l.module_id SET l.review_status='aprovada' WHERE m.course_id=?")->execute([$courseId]);$vs=videoCourseState($pdo,$courseId);ck($checks,'pedagogy_approved',$vs['pedagogical_ok']);
$outline='';foreach($pdo->query('SELECT m.position mp,m.title mt,l.position lp,l.title lt FROM modules m JOIN lessons l ON l.module_id=m.id WHERE m.course_id='.$courseId.' ORDER BY m.position,l.position')->fetchAll() as $r){$outline.='M'.$r['mp'].' '.$r['mt'].' A'.$r['lp'].' '.$r['lt']."\n";}$types=['slides','apostila','exercicios','avaliacao','pagina_venda','certificado'];$modes=[];foreach($types as $t){[$at,$ac,$am]=courseEngineGenerateMaterial($course,$outline,courseEngineSourceContext($pdo,$courseId),courseEngineLessonContext($pdo,$courseId),$t);$modes[]=$am;$s=$pdo->prepare("INSERT INTO course_assets(course_id,asset_type,title,content,status,engine_mode) VALUES(?,?,?,?,'gerado',?)");$s->execute([$courseId,$t,$at,$ac,$am]);}$vs=videoCourseState($pdo,$courseId);ck($checks,'package_6_of_6',$vs['package_ok'],'assets='.$vs['assets_count']);ck($checks,'materials_broker_used',in_array('centro_ia_broker_v1',$modes,true),implode(',',$modes));
$s=$pdo->prepare('INSERT INTO students(name,email) VALUES(?,?)');$s->execute(['Aluno E2E HML','e2e@example.invalid']);$studentId=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO enrollments(student_id,course_id,enrollment_type,status,payment_status,amount) VALUES(?,?,'individual','matriculado','pendente',100)");$s->execute([$studentId,$courseId]);$eid=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO enrollment_charges(enrollment_id,description,amount,due_date,status) VALUES(?,'E2E',100,CURDATE(),'pendente')");$s->execute([$eid]);$cid=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO enrollment_payments(enrollment_id,charge_id,amount,payment_method,paid_at,status) VALUES(?,?,100,'e2e',NOW(),'confirmado')");$s->execute([$eid,$cid]);financeReconcileCharge($pdo,$cid);$fs=financeEnrollmentSummary($pdo,$eid);ck($checks,'finance_paid',$fs['balance']<=0.009);
$pdo->prepare('INSERT INTO course_academic_rules(course_id,minimum_grade,require_all_lessons,require_all_attendance_records) VALUES(?,70,1,1)')->execute([$courseId]);foreach($pdo->query('SELECT l.id FROM lessons l JOIN modules m ON m.id=l.module_id WHERE m.course_id='.$courseId)->fetchAll(PDO::FETCH_COLUMN) as $lid){$s=$pdo->prepare("INSERT INTO lesson_progress(enrollment_id,lesson_id,status,watched_seconds,total_seconds,percent_complete,completed_at) VALUES(?,?,'concluida',600,600,100,NOW())");$s->execute([$eid,$lid]);}$s=$pdo->prepare("INSERT INTO assessments(course_id,title,max_score,weight,required,active) VALUES(?,'E2E',100,1,1,1)");$s->execute([$courseId]);$aid=(int)$pdo->lastInsertId();$s=$pdo->prepare("INSERT INTO assessment_results(assessment_id,enrollment_id,score,status,evaluated_at) VALUES(?,?,90,'avaliado',NOW())");$s->execute([$aid,$eid]);$el=academicEligibilityState($pdo,$eid);ck($checks,'academic_eligible',$el['eligible'],implode('|',$el['pending']));$done=academicSyncCompletion($pdo,$eid);ck($checks,'academic_completed',$done['status']==='concluido');$cert=academicIssueCertificate($pdo,$eid);ck($checks,'certificate_issued',($cert['status']??'')==='emitido');
$pdo->prepare("INSERT INTO course_video_settings(course_id,provider,account_mode,quota_minutes,visual_approved,real_submission_enabled) VALUES(?,'heygen','vitrine_managed',999,0,0)")->execute([$courseId]);$vs=videoCourseState($pdo,$courseId);ck($checks,'video_visual_gate_blocks',!$vs['visual_approved']&&!$vs['real_submission_enabled']);$pdo->prepare('UPDATE course_video_settings SET visual_approved=1 WHERE course_id=?')->execute([$courseId]);$q=videoSyncQueue($pdo,$courseId);$vs=videoCourseState($pdo,$courseId);ck($checks,'video_queue_ready',$q===$lessons&&$vs['visual_approved'],'queued='.$q);ck($checks,'heygen_real_submission_blocked',!$vs['real_submission_enabled']);echo json_encode(['ok'=>true,'checks'=>$checks],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
}catch(Throwable $e){$failed=true;echo json_encode(['ok'=>false,'error'=>get_class($e).':'.$e->getMessage(),'checks'=>$checks],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";}finally{try{if(isset($pdo)&&$courseId>0)$pdo->prepare('DELETE FROM courses WHERE id=?')->execute([$courseId]);if(isset($pdo)&&$studentId>0)$pdo->prepare('DELETE FROM students WHERE id=?')->execute([$studentId]);}catch(Throwable $x){}}if($failed)exit(1);'''


def main() -> int:
    inspect = subprocess.run(["docker", "inspect", TARGET_CONTAINER], text=True, capture_output=True)
    if inspect.returncode != 0:
        print(json.dumps({"ok": False, "error": "runtime_unavailable"}))
        return 1
    item = json.loads(inspect.stdout)[0]
    labels = item.get("Config", {}).get("Labels", {}) or {}
    if not item.get("State", {}).get("Running") or labels.get("com.docker.compose.project") != "cursos-ia-mvp" or labels.get("com.docker.compose.service") != "app":
        print(json.dumps({"ok": False, "error": "runtime_identity_mismatch"}))
        return 1
    proc = subprocess.run(["docker", "exec", "-w", "/var/www/html", TARGET_CONTAINER, "php", "-r", PHP], text=True, capture_output=True, timeout=900)
    sys.stdout.write(proc.stdout)
    if proc.stderr:
        sys.stderr.write(proc.stderr[-4000:])
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
