services:
  hml-center:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitrine_hml_center
    restart: unless-stopped
    environment:
      PORT: 8080
      ROUTING_REGISTRY: /app/routes.json
      HML_CENTER_USER: ${HML_CENTER_USER:?HML_CENTER_USER obrigatorio}
      HML_CENTER_PASSWORD: ${HML_CENTER_PASSWORD:?HML_CENTER_PASSWORD obrigatorio}
    volumes:
      - ../routes.json:/app/routes.json:ro
    networks:
      - vitrine_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=16m
    pids_limit: 64
    mem_limit: 128m
    cpus: 0.25

networks:
  vitrine_net:
    external: true
    name: vitrine_net
